spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-52-213-173-172.eu-west-1.compute.amazonaws.com:5432/d33s4fldbf6l4r
    username: lvoymnzynhzmap
    password: f70785a852a306b95b2180dfea7ef9c38527f5ae2b7f98239cfc399501164a85
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

swagger:
  host:
    url: localhost:8080
    path:

management:
  info:
    git:
      mode: simple
  endpoints:
    web:
      base-path: /_monitoring
      exposure:
        include: '*'